WIP: Introduce component library and major UI improvements
v3xlabs/edgeserver pull request #148
Opened 2022-10-18 17:10 UTC by robiot

![image](https://user-images.githubusercontent.com/68228472/196498574-1d684bd1-f094-4864-9b9c-4a3a51896474.png)
![image](https://user-images.githubusercontent.com/68228472/196498609-67aa7581-12a5-4589-8d1f-554989500c4b.png)
![image](https://user-images.githubusercontent.com/68228472/196498732-96aab526-5bac-4e42-993d-d217abb2b6b4.png)
![image](https://user-images.githubusercontent.com/68228472/196498770-03b0135b-95a4-41e0-887e-14f28bf2391b.png)

2022-10-18 17:31 UTC, robiot commented
This "component library" is completely unused in this PR. 
A new PR will be created for migrating to the component library.

2022-10-18 19:27 UTC, robiot commented
![image](https://user-images.githubusercontent.com/68228472/196525417-96833486-d914-4f8c-b4e9-e47faaec5546.png)
![image](https://user-images.githubusercontent.com/68228472/196525448-9118b2b0-bfed-4570-9825-ceec85e28f26.png)

With these components, the design will stay consistent across the whole page.

2022-10-21 16:36 UTC, lucemans commented on apps/app/src/components/Modal.tsx
> +                    <div className="relative bg-white rounded-lg shadow dark:bg-neutral-900 border-neutral-300 dark:border-neutral-800 border">
😏

2022-10-21 16:37 UTC, lucemans commented on apps/app/src/pages/login/StepOne.tsx
> +            </div> */}
Thank you

2022-10-21 16:37 UTC, lucemans commented on apps/app/tailwind.config.js
> +                // },
?

2022-10-21 16:50 UTC, lucemans commented
Preferrably use `Link` from `react-router` so that the SPA routing functionality works!

2022-10-31 18:17 UTC, lucemans requested changes

2022-10-31 18:17 UTC, lucemans commented on packages/components/vite.config.ts
> +        // },
?
```suggestion
```

2022-10-31 18:33 UTC, lucemans approved these changes
LGTM

2022-10-31 18:33 UTC, merged